FROM node:16-alpine

ENV NODE_ENV production

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
RUN npm ci --only=production
COPY . .
RUN npm run build

FROM nginx
ENV NODE_ENV production

ARG BACKEND_IP

COPY --from=0 /app/build /usr/share/nginx/html

COPY --from=0 /app/nginx/templates/default.conf.template /etc/nginx/conf.d/default.conf.template

COPY --from=0 /app/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
