FROM node:16-alpine

ENV NODE_ENV production

WORKDIR /app

ENV REACT_APP_API_URL https://blog.leevi.dev/api

COPY package*.json ./
COPY tsconfig.json ./
RUN npm ci --emit=dev
COPY . .
RUN npm run build

FROM nginx:1.23-alpine
ENV NODE_ENV production

COPY --from=0 /app/build /usr/share/nginx/html

COPY --from=0 /app/nginx/templates/default.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
