FROM node:16-alpine

ENV NODE_ENV production

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
RUN npm ci --only=production
COPY . .
RUN npm run build

FROM nginx
ENV NODE_ENV production

ARG BACKEND_IP

COPY --from=0 /app/build /usr/share/nginx/html
COPY ./client/nginx/templates /etc/nginx/templates

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
