version: "3.8"

services:
  backend:
    container_name: blog-backend
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: blog-store
