services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: blog-db
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    environment:
      - POSTGRES_PASSWORD=Kill4123
      - POSTGRES_DB=memorylane
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
