FROM node:16-alpine

WORKDIR /usr/src/app

RUN apk update && \
    apk upgrade && \
    apk add --no-cache dumb-init

COPY package*.json ./
COPY tsconfig.json ./
COPY . .

RUN npm ci && npm i -g typescript && npm run build

FROM node:16-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --only=production
COPY --from=0 /usr/src/app/dist ./dist 

EXPOSE 5000

USER node

CMD [ "npm", "start" ]
