FROM node:16-alpine

WORKDIR /app
ENV NODE_ENV=development

COPY package*.json ./
COPY tsconfig.json ./
RUN npm install && npm install -g typescript
COPY . . 

RUN mkdir -p dist && chown node:node dist

EXPOSE 5000

USER node

CMD [ "npm", "run", "dev" ]
