version: "3.9"

services:
  server:
    image: ghcr.io/leeviko/blog-backend
    container_name: blog-backend
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: server-store
