version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://store
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: store
