name: Build and publish images and deploy to server

on:
  push:
    branches: [master]
    paths:
      - "client/**"
      - ".github/workflows/**"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Frontend image
        run: |
          cd client
          docker build -f Dockerfile.prod -t ghcr.io/leeviko/blog-frontend .
          docker push ghcr.io/leeviko/blog-frontend
      - name: Backend image
        run: |
          cd server
          docker compose -f docker-compose.prod.yml build
          docker compose -f docker-compose.prod.yml push
  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /srv/www/blog/backend
            sh init.sh
            cd /srv/www/blog/frontend
            sh init.sh
