name: Build and publish backend images

on:
  push:
    branches: [master]
    paths:
      - "server/**"
      - ".github/workflows/**"
      - "docker-compose*.yml"

defaults:
  run:
    working-directory: server

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.SERVER_ENV_PROD }}" > .env
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        run: docker compose -f docker-compose.prod.yml build
      - name: idk
        run: cat docker-compose.prod.yml
      - name: List images
        run: docker images
      - name: Push images to Container Registry
        run: docker compose -f docker-compose.prod.yml push
