name: Build and publish frontend images

on:
  push:
    branches: [master]
    paths:
      - "client/**"
      - ".github/workflows/**"
      - "docker-compose*.yml"

defaults:
  run:
    working-directory: client

jobs:
  build-and-push-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch ./nginx/.env
          echo "${{ secrets.SERVER_NGINX_ENV_PROD }}" > ./nginx/.env
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        run: docker compose -f docker-compose.prod.yml --profile client build
      - name: Push images to Container Registry
        run: docker compose -f docker-compose.prod.yml --profile client push
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_FRONTEND_HOST }}
          username: ${{ secrets.SSH_FRONTEND_USERNAME }}
          key: ${{ secrets.SSH_FRONTEND_KEY }}
          passphrase: ${{ secrets.SSH_FRONTEND_PASSWORD }}
          port: ${{ secrets.SSH_FRONTEND_PORT }}
          fingerprint: ${{ secrets.SSH_FRONTEND_FINGERPRINT }}
          script: whoami
