name: Build and publish backend images

on:
  push:
    branches: [master]
    paths:
      - "server/**"
      - ".github/workflows/**"
      - "docker-compose*.yml"

defaults:
  run:
    working-directory: server

jobs:
  build-and-push-backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.SERVER_ENV_PROD }}" > .env
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        run: docker compose -f docker-compose.prod.yml --profile server build
      - name: Push images to Container Registry
        run: docker compose -f docker-compose.prod.yml --profile server push
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_BACKEND_HOST }}
          username: ${{ secrets.SSH_BACKEND_USERNAME }}
          key: ${{ secrets.SSH_BACKEND_KEY }}
          passphrase: ${{ secrets.SSH_BACKEND_PASSWORD }}
          port: ${{ secrets.SSH_BACKEND_PORT }}
          fingerprint: ${{ secrets.SSH_BACKEND_FINGERPRINT }}
          script: whoami
